name: build jars
on: [pull_request,push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.9'
      - uses: actions/upload-artifact@v2
        with:
          name: producedJars
          path: build/libs/*
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        os: [ubuntu-lastest, windows-latest,macos-latest]
        java: [8, 11]

    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: gradle test
        run: |
          ./gradlew test
